/**
 * Reads `.env` from the project root (if present) and writes `src/environments/environment.app.ts`.
 * Safe defaults match `.env.example` when variables are missing.
 * Run automatically via postinstall, prestart, and prebuild.
 */
const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const outPath = path.join(root, 'src', 'environments', 'environment.app.ts');

if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath });
}

/** Default API/socket host when env vars are unset (same Cloudflare tunnel as backend). */
const DEFAULT_PUBLIC_API_ORIGIN =
  'https://transaction-european-squad-strengthen.trycloudflare.com';

function str(key, fallback = '') {
  const v = process.env[key];
  if (v === undefined || v === '') return fallback;
  return v;
}

function bool(key, fallback) {
  const v = process.env[key];
  if (v === undefined || v === '') return fallback;
  return /^(1|true|yes|on)$/i.test(String(v).trim());
}

const production = bool('FBP_PRODUCTION', false);
const useDummyFranchiseAuth = bool('USE_DUMMY_FRANCHISE_AUTH', false);

const env = {
  production,
  googleMapsApiKey: str('GOOGLE_MAPS_API_KEY', ''),
  useDummyFranchiseAuth,
  franchiseDemoLogin: {
    aimId: str('FRANCHISE_DEMO_AIM_ID', 'AIM1001'),
    password: str('FRANCHISE_DEMO_PASSWORD', 'demo123'),
  },
  franchiseApiBaseUrl: str(
    'FRANCHISE_API_BASE_URL',
    `${DEFAULT_PUBLIC_API_ORIGIN}/api`,
  ),
  adminApiBaseUrl: str(
    'ADMIN_API_BASE_URL',
    `${DEFAULT_PUBLIC_API_ORIGIN}/api/admin`,
  ),
  franchiseRegistrationApiUrl: str(
    'FRANCHISE_REGISTRATION_API_URL',
    DEFAULT_PUBLIC_API_ORIGIN,
  ),
  biddingSocketUrl: str('BIDDING_SOCKET_URL', DEFAULT_PUBLIC_API_ORIGIN),
  razorpayKey: str('RAZORPAY_KEY_ID', ''),
};

const header = `/* eslint-disable */
/* Generated by scripts/sync-env.cjs — do not edit. Re-run: npm run sync-env */
`;

const body = `export const environment = ${JSON.stringify(env, null, 2)} as const;
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, header + body, 'utf8');
console.log('[sync-env] wrote', path.relative(root, outPath));
